const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DONATE: "/donate",
  DONATE_DETAIL: "/donate/:campaignId",
  MY_DONATIONS: "/my-donations",
  APPLY_ORGANIZER: "/apply-organizer",
  APPLICATION_STATUS: "/application-status",
  MY_CAMPAIGNS: "/my-campaigns",
  ORGANIZER_DASHBOARD: "/organizer/dashboard",
  ORGANIZER_PROFILE: "/organizer/profile",
  CREATE_CAMPAIGN: "/campaign/new",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_CAMPAIGNS: "/admin/campaigns",
  ADMIN_USERS: "/admin/users",
  ADMIN_DONATIONS: "/admin/donations",
  ADMIN_ACTIVITIES: "/admin/activities",
  ADMIN_APPLICATIONS: "/admin/applications",
  ADMIN_ORGANIZER_PROFILES: "/admin/organizer-profiles",
  ADMIN_WITHDRAWALS: "/admin/withdrawals",
  WITHDRAWAL_REQUEST: "/withdrawal-request/:campaignId",
  ABOUT: "/about",
  DASHBOARD: "/dashboard",
  NOTIFICATIONS: "/notifications",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  OTP_VERIFICATION: "/otp-verification",
};

export default ROUTES;
